### ISSUE TITLE
Make Default Credential Provider -  Help Wanted

### ISSUE THREAD

**Issue by subu1979** [lithnet/windows-credential-provider#1]
Hi 

Thanks for the project.

Without hiding the other credential providers, can you make this the default Credential Provider??

Any thoughts on this?

**Comment by subu1979** [comment]
![c#_desktop_cp](https://github.com/lithnet/windows-credential-provider/assets/3286581/351ca967-5a19-469a-8a21-b3a7faa145c3)

User tile is not displaying, using the below code

yield return new CredentialProviderLogoControl(ControlKeys.ImageUserTile, "Credential User Tile logo", Resource.CyLock);

**Comment by ryannewington** [comment]
@subu1979 this library is just a wrapper around the windows credential provider interface - for a detailed understanding of options and how it all works I recommend reading  this guide https://go.microsoft.com/fwlink/?LinkId=717287

I don't believe you can force a tile to be default. 

When you say that the user tile is not showing, can you explain what you mean? Is that not your custom logo shown below where it says sign-in options. What are you expecting to see?

**Comment by subu1979** [comment]
What's the difference between ImageCredentialProvider & ImageUserTile

**Comment by ryannewington** [comment]
In the document linked above, you can read about CPFT_TILE_IMAGE and CPFG_CREDENTIAL_PROVIDER_LOGO which are represented by those object types.

**Comment by subu1979** [comment]
> CPFT_TILE_IMAGE

User Tile image is not changing (even i had made bmp with 72x72)
