### ISSUE TITLE
when I install in window 11 its does not work ?

### ISSUE THREAD

**Issue by skm00** [lithnet/windows-credential-provider#11]
when I install in window 11 its does not work ?

**Comment by ryannewington** [comment]
the provider itself definitely works on windows 11. we use it as part of our commercial product offerings.

**Comment by iLikeToCode** [comment]
@ryannewington might wanna close this for the sake of not leaving issues open. It definitely works on windows 11 as I, for whatever reason, made a TOTP login for windows 11

**Comment by skm00** [comment]
What is the cost of window 11 ?

**Comment by iLikeToCode** [comment]
Literally? No cost upgrading from windows 10, I think its roughly 100$ tor 11 home and double that for pro

**Comment by skm00** [comment]
I need for the window 11 . I am developer .if you have any free thing let
me know.
