### ISSUE TITLE
How can I set an icon?

### ISSUE THREAD

**Issue by iLikeToCode** [lithnet/windows-credential-provider#14]
How can I set an icon for the credential provider? Right now its a transparent box I can click on

**Comment by iLikeToCode** [comment]
I'll check the closed issue, didn't see it before.

**Comment by ryannewington** [comment]
Example is here

https://github.com/lithnet/windows-credential-provider/blob/8ad14a2e2ee85b4b545026e4ab19552cc5b1bb3c/src/samples/Lithnet.CredentialProvider.Sample.net472.x64/TestCredentialProviderNet472x64.cs#L39

**Comment by iLikeToCode** [comment]
@ryannewington btw, in the NETF 4.7.2 example in ControlKeys.cs you spelt 'User' wrong in one of the IDs, I can make a PR if you want.

**Comment by iLikeToCode** [comment]
Ill make one anyway
