### ISSUE TITLE
Change the adjacent control of the submit button

### ISSUE THREAD

**Issue by Maxhy** [lithnet/windows-credential-provider#20]
Sometimes the submit button should be adjacent to one or another control depending if such controls are displayed or not.

It is currently impossible to change the adjacent control whereas the interface `ICredentialProviderCredentialEvents` has such capability with `SetFieldSubmitButton`.

I believe a new method `ChangeAdjacentControl` should be added to `SubmitButtonControl` class to properly call the event and update the instance properties. What do you think @ryannewington?

**Comment by ryannewington** [comment]
what about doing it this way https://github.com/lithnet/windows-credential-provider/pull/21

**Comment by Maxhy** [comment]
Yes 👍 . The API is cleaner this way indeed. Thanks!
