### ISSUE TITLE
.net 8 support

### ISSUE THREAD

**Issue by IvanSantosGonz** [lithnet/windows-credential-provider#8]
Hello, thank you for the Credential Provider.
Would it be possible to add support for .NET 8 since .NET 6 will be out of support in November 2024?

**Comment by ryannewington** [comment]
hi @IvanSantosGonz 

Are you saying it doesn't work in .NET 8?

**Comment by IvanSantosGonz** [comment]
Yes, .Net 6 and .Net 7 works well but .Net 8 doesn't work

**Comment by ryannewington** [comment]
Can you give me some more information on the problem you are experiencing? Any errors?

**Comment by IvanSantosGonz** [comment]
I just build the example with .Net 6 and 7 and installed using the `Register-CredentialProvider -File C:\path-to-your-provider.dll` command and I can see the new credential provider in Windows Login page.

I did the same with .Net 8, the build goes well but after install it, nothing appears in the Windows Login page.

**Comment by IvanSantosGonz** [comment]
Hello @ryannewington! Do you have some update regarding to this?

Thanks in advance!

**Comment by ryannewington** [comment]
Hi @IvanSantosGonz my apologies, I haven't really had time to look into this. However, I just built a small .net 8 minimal project using the existing library, and it worked fine for me.

There must be something else going on. Keep in mind you wont be able to combine different .NET versions across credential providers. COM can't load the .NET framework assemblies and .NET core assemblies into the same process - you start getting all sorts of weird errors. So if you have any other .NET based cred providers registered, disable them while testing to rule out any conflicts.

These can be quite complex to troubleshoot, and unfortunately I don't have the time to help you with this one. However, if you do find an issue, I'd be happy to accept a fix via pull request. At a minimum  we'd need steps to reproduce or a viable sample app.

My personal recommendation, skip .NET core variants and stick with .NET framework 4 if you can. It's got 10 years of support life, extended every time they release a version of Windows with it built in. Your cred provider will always be running on a supported and patched runtime as long as the windows system its running on is still in support.

**Comment by IvanSantosGonz** [comment]
My fault, I was combining different .NET versions across credential providers.
After removing some .Net 8 incompatible dependencies of the project everything is working well from my side in .Net 8. 
So this issue can be closed because everything is working well with .Net 8. 

Thank you so much for your help.
