### ISSUE TITLE
How I can changed transperent icon to own icon

### ISSUE THREAD

**Issue by skm00** [lithnet/windows-credential-provider#9]
How I can changed transperent icon to own icon

**Comment by ryannewington** [comment]
Check the sample code for how it loads an embedded resource and sets it to the tile image.

https://github.com/lithnet/windows-credential-provider/blob/main/src/samples/Lithnet.CredentialProvider.Sample.net6.0.x64/TestCredentialProviderNet60x64.cs

**Comment by skm00** [comment]
Thanks
